[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 4321
  targetPort = 4321

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200